#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 12:12:23 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.zip
